export const ADD_KEGBEER = 'ADD_KEGBEER';
export const DELETE_KEGBEER = 'DELETE_KEGBEER';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const SELL_PINT = 'SELL_PINT';
export const TOGGLE_UPDATE = 'TOGGLE_UPDATE';
export const SELECT_KEGBEER = 'SELECT_KEGBEER';
export const DESELECT_KEGBEER = 'DESELECT_KEGBEER';